-- =====================================================================
--  NsiTransfer — физическая схема БД (PostgreSQL)
--  Сгенерировано по: AppDbContext.OnModelCreating + AppDbContextModelSnapshot
--  EF Core 8.0.27 / Npgsql, провайдер identity-by-default
--  БД: nsi_transfer (см. ConnectionStrings:DefaultConnection)
-- =====================================================================

-- ---------------------------------------------------------------------
--  Справочники (seed при начальной миграции)
-- ---------------------------------------------------------------------

-- 1. Справочник статусов отправления (Sending). Заполняется HasData.
CREATE TABLE "SendingStatuses" (
    "Id"          integer      NOT NULL,                   -- SendingStatusEnum (0,1,2,3,4,100,101,102,103)
    "Name"        varchar(256) NOT NULL,
    "Description" varchar(1024) NOT NULL,
    CONSTRAINT "PK_SendingStatuses" PRIMARY KEY ("Id")
);

-- 2. Справочник результатов публикации в RabbitMQ (Message.PublishingResultId).
--    Заполняется HasData.
CREATE TABLE "PublishingResults" (
    "Id"          integer      NOT NULL,                   -- RabbitMqPublishingResultEnum (0..6)
    "Name"        varchar(256) NOT NULL,
    "Description" varchar(1024) NOT NULL,
    CONSTRAINT "PK_PublishingResults" PRIMARY KEY ("Id")
);

-- 3. Реестр целевых узлов классификации Полинома (область поиска объектов).
--    Пополняется автоматически через JsonConfigurationWriter.WriteAtomicAsync
--    при изменении TargetReferenceNode в configuration.json.
CREATE TABLE "TargetReferenceNodes" (
    "Id"       integer         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ObjectId" integer         NOT NULL,                    -- ObjectId в API Полинома
    "TypeId"   integer         NOT NULL,                    -- IdentifiableObjectType (int)
    "Name"     text            NOT NULL,
    CONSTRAINT "PK_TargetReferenceNodes" PRIMARY KEY ("Id")
);


-- ---------------------------------------------------------------------
--  Основные таблицы
-- ---------------------------------------------------------------------

-- 4. Отправление — корневая сущность одного цикла синхронизации.
--    ActiveMarker + UNIQUE-индекс = БД-блокировка параллельных запусков:
--    активной может быть только одна запись (StatusId ∈ {Initiated, Pending}).
CREATE TABLE "Sendings" (
    "Id"                   uuid                      NOT NULL,
    "InitiatedAt"          timestamp with time zone  NOT NULL,        -- момент создания (UTC)
    "EndedAt"              timestamp with time zone  NULL,            -- терминальный момент (UTC), NULL пока активно
    "InitiatorName"        varchar(256)              NOT NULL,        -- кто/что запустил: "Фоновый сервис" | имя пользователя
    "StatusId"             integer                   NOT NULL,        -- FK -> SendingStatuses.Id
    "ActiveMarker"         boolean                   NULL,            -- true=активно, NULL=завершено. UNIQUE.
    "TargetReferenceNodeId" integer                  NOT NULL,        -- FK -> TargetReferenceNodes.Id
    CONSTRAINT "PK_Sendings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sendings_TargetReferenceNodes_TargetReferenceNodeId"
        FOREIGN KEY ("TargetReferenceNodeId") REFERENCES "TargetReferenceNodes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Sendings_SendingStatuses_StatusId"
        FOREIGN KEY ("StatusId") REFERENCES "SendingStatuses" ("Id")
);
CREATE UNIQUE INDEX "IX_Sendings_ActiveMarker"        ON "Sendings" ("ActiveMarker");   -- гарантирует единственную активную запись
CREATE        INDEX "IX_Sendings_TargetReferenceNodeId" ON "Sendings" ("TargetReferenceNodeId");

-- 5. Сообщение — пачка объектов Полинома, отправляемая одним publish в RabbitMQ.
--    SerializedMessage (jsonb) — фактический payload наружу.
CREATE TABLE "Messages" (
    "Id"                            bigint                    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "StartedCollectionFromPolynomAt" timestamp with time zone  NOT NULL, -- начало сбора данных
    "FinishedCollectionFromPolynomAt" timestamp with time zone NULL,     -- завершение сбора данных
    "SentAtQueue"                   timestamp with time zone  NULL,      -- момент BasicPublish + Ack
    "SerializedMessage"             jsonb                     NULL DEFAULT '{}'::jsonb,  -- payload наружу
    "PublishingResultId"            integer                   NOT NULL DEFAULT 0,        -- FK -> PublishingResults.Id
    "MessageType"                   integer                   NOT NULL,                  -- MessageTypeEnum: 1=FirstSend, 2=Retry
    "SendingId"                     uuid                      NOT NULL,                  -- FK -> Sendings.Id
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Sendings_SendingId"
        FOREIGN KEY ("SendingId") REFERENCES "Sendings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_PublishingResults_PublishingResultId"
        FOREIGN KEY ("PublishingResultId") REFERENCES "PublishingResults" ("Id")
);
CREATE INDEX "IX_Messages_SendingId" ON "Messages" ("SendingId");

-- 6. Журнал успешно собранных объектов Полинома в рамках одного Message.
CREATE TABLE "PolynomObjects" (
    "Id"                 bigint     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "MessageId"          bigint     NOT NULL,             -- FK -> Messages.Id
    "Name"               varchar(256) NOT NULL,
    "ClassificationCode" varchar(64) NULL,                -- вычисленный/существующий код классификатора
    "PolynomObjectId"    bigint     NOT NULL,             -- идентификатор объекта в API Полинома
    "PolynomTypeId"      integer    NOT NULL,             -- IdentifiableObjectType (int)
    CONSTRAINT "PK_PolynomObjects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PolynomObjects_Messages_MessageId"
        FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_PolynomObjects_ClassificationCode" ON "PolynomObjects" ("ClassificationCode");
CREATE INDEX "IX_PolynomObjects_MessageId"          ON "PolynomObjects" ("MessageId");
CREATE INDEX "IX_PolynomObjects_Name"               ON "PolynomObjects" ("Name");

-- 7. Журнал ошибок вычисления кода классификатора по объекту.
--    Используется механизмом RetryFailedObjectsAsync: при следующей
--    синхронизации записи перепроверяются и удаляются при успехе.
CREATE TABLE "PolynomObjectFailures" (
    "Id"             bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "MessageId"      bigint                   NOT NULL,              -- FK -> Messages.Id (контекст ошибки)
    "PolynomObjectId" integer                 NOT NULL,
    "PolynomTypeId"  integer                  NOT NULL,
    "ObjectName"     varchar(256)             NOT NULL,
    "FailureType"    text                     NOT NULL,               -- PolynomObjectFailureTypeEnum (строкой)
    "FailedAt"       timestamp with time zone NOT NULL,
    "ErrorMessage"   text                     NULL,
    CONSTRAINT "PK_PolynomObjectFailures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PolynomObjectFailures_Messages_MessageId"
        FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_PolynomObjectFailures_MessageId" ON "PolynomObjectFailures" ("MessageId");

-- 8. Журнал ошибок на уровне сообщения (сбой сбора данных ИЛИ публикации).
--    Связь с Messages 1:1.
CREATE TABLE "MessageFailures" (
    "Id"                  bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FailedAt"            timestamp with time zone NOT NULL,
    "FailureDescription"  text                     NOT NULL,           -- сериализованный Exception либо текст ошибки
    "FailureReasonTitle"  varchar(1024)            NOT NULL,           -- короткий заголовок причины
    "MessageId"           bigint                   NOT NULL,           -- FK -> Messages.Id, UNIQUE
    CONSTRAINT "PK_MessageFailures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MessageFailures_Messages_MessageId"
        FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_MessageFailures_MessageId" ON "MessageFailures" ("MessageId");


-- ---------------------------------------------------------------------
--  Email-нотификации (об ошибках синхронизации и работы сервиса)
-- ---------------------------------------------------------------------

-- 9. Реестр уникальных адресов получателей.
CREATE TABLE "EmailRecipients" (
    "Id"          bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EmailAddress" varchar(256) NOT NULL,
    CONSTRAINT "PK_EmailRecipients" PRIMARY KEY ("Id")
);

-- 10. Отправленное email-сообщение.
CREATE TABLE "EmailMessages" (
    "Id"      bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SentAt"  timestamp with time zone NOT NULL,
    "Subject" varchar(998)             NOT NULL,            -- RFC 5322: макс. длина строки заголовка
    "Body"    text                     NOT NULL,            -- HTML-тело (см. EmailService)
    "Status"  text                     NOT NULL,            -- EmailStatus строкой: 'Sent' | 'Failed'
    CONSTRAINT "PK_EmailMessages" PRIMARY KEY ("Id")
);

-- 11. Ошибка отправки конкретного EmailMessage (1:1).
CREATE TABLE "EmailFailures" (
    "Id"            bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EmailMessageId" bigint NOT NULL,
    "ErrorMessage"  text   NOT NULL,
    CONSTRAINT "PK_EmailFailures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailFailures_EmailMessages_EmailMessageId"
        FOREIGN KEY ("EmailMessageId") REFERENCES "EmailMessages" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_EmailFailures_EmailMessageId" ON "EmailFailures" ("EmailMessageId");

-- 12. M:N связка EmailMessage ↔ EmailRecipient.
CREATE TABLE "EmailMessagesToEmailRecipients" (
    "MessageId"   bigint NOT NULL,
    "RecipientId" bigint NOT NULL,
    CONSTRAINT "PK_EmailMessagesToEmailRecipients" PRIMARY KEY ("MessageId", "RecipientId"),
    CONSTRAINT "FK_EmailMessagesToEmailRecipients_EmailMessages_MessageId"
        FOREIGN KEY ("MessageId") REFERENCES "EmailMessages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmailMessagesToEmailRecipients_EmailRecipients_RecipientId"
        FOREIGN KEY ("RecipientId") REFERENCES "EmailRecipients" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_EmailMessagesToEmailRecipients_RecipientId"
    ON "EmailMessagesToEmailRecipients" ("RecipientId");


-- =====================================================================
--  Сиды справочников (применяются при начальной миграции)
-- =====================================================================

INSERT INTO "SendingStatuses" ("Id", "Name", "Description") VALUES
  (0,   'Unknown',                                    'Неизвестный статус, отсутствие статуса'),
  (1,   'Initiated',                                  'Инициировано начало отправления'),
  (2,   'Pending',                                    'В процессе сборки и отправления сообщений'),
  (3,   'Completed',                                  'Все сообщения из отправления успешно собраны и отправлены в брокер сообщений'),
  (4,   'EmptySending',                               'Сформировано пустое сообщение. Новых изменений в системе Полином не было найдено'),
  (100, 'ErrorUnknown',                               'Неизвестная ошибка'),
  (101, 'ErrorOccuredWhilePreparing',                 'Ошибка при подготовке отправления'),
  (102, 'ErrorOccuredWhileCollectingDataForMessage',  'Ошибка при сборе данных для одного из сообщений в отправлении'),
  (103, 'ErrorOccuredWhilePublishingMessage',         'Ошибка при публикации одного из сообщений в отправлении');

INSERT INTO "PublishingResults" ("Id", "Name", "Description") VALUES
  (0, 'Unknown',                       'Неизвестная ошибка'),
  (1, 'Ack',                           'Подтверждение от RabbitMQ'),
  (2, 'Nack',                          'Отрицательное подтверждение от RabbitMQ'),
  (3, 'TimedOut',                      'Превышено время ожидания подтверждения от RabbitMQ'),
  (4, 'ConnectionBlocked',             'Подключение к RabbitMQ было заблокировано'),
  (5, 'Failed',                        'Не удалось подключиться к RabbitMQ или опубликовать сообщение в очередь RabbitMQ после нескольких попыток'),
  (6, 'FailedDuringInformationCollection', 'Не удалось собрать объекты со свойствами перед формированием самого сообщения для отправки');


-- =====================================================================
--  Полезные индексы для аналитики/эксплуатации (не генерируются EF,
--  добавить вручную при необходимости)
-- =====================================================================
-- CREATE INDEX "IX_Sendings_StatusId_InitiatedAt" ON "Sendings" ("StatusId", "InitiatedAt" DESC);
-- CREATE INDEX "IX_PolynomObjects_PolynomObjectId_PolynomTypeId"
--     ON "PolynomObjects" ("PolynomObjectId", "PolynomTypeId");
-- CREATE INDEX "IX_PolynomObjectFailures_PolynomObjectId_PolynomTypeId"
--     ON "PolynomObjectFailures" ("PolynomObjectId", "PolynomTypeId");


-- =====================================================================
--  Примечания
-- =====================================================================
-- 1. Все timestamp with time zone хранят UTC (DateTime.UtcNow в коде).
--    Точность — 3 знака после секунды (HasPrecision(3)).
-- 2. SerializedMessage имеет DEFAULT '{}'::jsonb, чтобы CanBeNull + конвертер
--    в OnModelCreating не порождали NULL при пустом payload.
-- 3. PolynomObjectFailure.FailureType хранится строкой
--    (HasConversion<string>()), аналогично EmailMessage.Status.
-- 4. PolynomObjectId в PolynomObject — bigint (long), а в PolynomObjectFailure
--    — integer (int). Это историческое расхождение в миграциях.
-- 5. Каскадное удаление: Messages → PolynomObjects / PolynomObjectFailures /
--    MessageFailures; Sendings → Messages; EmailMessages → EmailFailures /
--    связку M:N. Удаление Sending'а зачищает всю его историю.
