// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NsiTransfer.DAL.Db.Context;

#nullable disable

namespace NsiTransfer.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715102658_AddTargetReferenceNodeIdColumnInSendingsTable")]
    partial class AddTargetReferenceNodeIdColumnInSendingsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmailMessagesToEmailRecipients", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.HasKey("MessageId", "RecipientId");

                    b.HasIndex("RecipientId");

                    b.ToTable("EmailMessagesToEmailRecipients");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.EmailFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EmailMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId")
                        .IsUnique();

                    b.ToTable("EmailFailures");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.EmailMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(998)");

                    b.HasKey("Id");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.EmailRecipient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("EmailRecipients");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FinishedCollectionFromPolynomAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublishingResultId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SendingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAtQueue")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerializedMessage")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedCollectionFromPolynomAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SendingId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.MessageFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FailedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReasonTitle")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("MessageFailures");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.MessagePublishingResult", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("PublishingResults");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Неизвестная ошибка",
                            Name = "Unknown"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Подтверждение от RabbitMQ",
                            Name = "Ack"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Отрицательное подтверждение от RabbitMQ",
                            Name = "Nack"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Превышено время ожидания подтверждения от RabbitMQ",
                            Name = "TimedOut"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Подключение к RabbitMQ было заблокировано",
                            Name = "ConnectionBlocked"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Не удалось подключиться к RabbitMQ или опубликовать сообщение в очередь RabbitMQ после нескольких попыток",
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Не удалось собрать объекты со свойствами перед формированием самого сообщения для отправки",
                            Name = "FailedDuringInformationCollection"
                        });
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.PolynomObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<long>("PolynomObjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("PolynomObjects");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Sending", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ActiveMarker")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InitiatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiatorName")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReferenceNodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActiveMarker")
                        .IsUnique();

                    b.HasIndex("TargetReferenceNodeId");

                    b.ToTable("Sendings");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.SendingStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SendingStatuses");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Неизвестный статус, отсутствие статуса",
                            Name = "Unknown"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Инициировано начало отправления",
                            Name = "Initiated"
                        },
                        new
                        {
                            Id = 2,
                            Description = "В процессе сборки и отправления сообщений",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Все сообщения из отправления успешно собраны и отправлены в брокер сообщений",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Сформировано пустое сообщение. Новых изменений в системе Полином не было найдено",
                            Name = "EmptySending"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Неизвестная ошибка",
                            Name = "ErrorUnknown"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Ошибка при подготовке отправления",
                            Name = "ErrorOccuredWhilePreparing"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Ошибка при сборе данных для одного из сообщений в отправлении",
                            Name = "ErrorOccuredWhileCollectingDataForMessage"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Ошибка при публикации одного из сообщений в отправлении",
                            Name = "ErrorOccuredWhilePublishingMessage"
                        });
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.TargetReferenceNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TargetReferenceNodes");
                });

            modelBuilder.Entity("EmailMessagesToEmailRecipients", b =>
                {
                    b.HasOne("NsiTransfer.DAL.Db.Entities.EmailMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NsiTransfer.DAL.Db.Entities.EmailRecipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.EmailFailure", b =>
                {
                    b.HasOne("NsiTransfer.DAL.Db.Entities.EmailMessage", "EmailMessage")
                        .WithOne("Failure")
                        .HasForeignKey("NsiTransfer.DAL.Db.Entities.EmailFailure", "EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Message", b =>
                {
                    b.HasOne("NsiTransfer.DAL.Db.Entities.Sending", "Sending")
                        .WithMany("Messages")
                        .HasForeignKey("SendingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sending");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.MessageFailure", b =>
                {
                    b.HasOne("NsiTransfer.DAL.Db.Entities.Message", "Message")
                        .WithOne("MessageFailure")
                        .HasForeignKey("NsiTransfer.DAL.Db.Entities.MessageFailure", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.PolynomObject", b =>
                {
                    b.HasOne("NsiTransfer.DAL.Db.Entities.Message", "Message")
                        .WithMany("PolynomObjects")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Sending", b =>
                {
                    b.HasOne("NsiTransfer.DAL.Db.Entities.TargetReferenceNode", "TargetReferenceNode")
                        .WithMany()
                        .HasForeignKey("TargetReferenceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetReferenceNode");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.EmailMessage", b =>
                {
                    b.Navigation("Failure");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Message", b =>
                {
                    b.Navigation("MessageFailure");

                    b.Navigation("PolynomObjects");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Sending", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
