// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NsiTransfer.DAL.Db.Context;

#nullable disable

namespace NsiTransfer.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625121836_IntroduceSendingEntityAndRefactorRelationships")]
    partial class IntroduceSendingEntityAndRefactorRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetReferenceNodeName")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<int>("TargetReferenceNodeObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReferenceNodeTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FinishedCollectionFromPolynomAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublishingResultId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAtQueue")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerializedMessage")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedCollectionFromPolynomAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.MessageFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FailedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReasonTitle")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("MessageFailures");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.MessagePublishingResult", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("PublishingResults");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Неизвестная ошибка",
                            Name = "Unknown"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Подтверждение от RabbitMQ",
                            Name = "Ack"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Отрицательное подтверждение от RabbitMQ",
                            Name = "Nack"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Превышено время ожидания подтверждения от RabbitMQ",
                            Name = "TimedOut"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Подключение к RabbitMQ было заблокировано",
                            Name = "ConnectionBlocked"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Не удалось подключиться к RabbitMQ или опубликовать сообщение в очередь RabbitMQ после нескольких попыток",
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Не удалось собрать объекты со свойствами перед формированием самого сообщения для отправки",
                            Name = "FailedDuringInformationCollection"
                        });
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.PolynomObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<long>("PolynomObjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("PolynomObjects");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Sending", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InitiatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiatorName")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sendings");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.SendingStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SendingStatuses");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Неизвестный статус, отсутствие статуса",
                            Name = "Unknown"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Инициировано начало отправления",
                            Name = "Initiated"
                        },
                        new
                        {
                            Id = 2,
                            Description = "В процессе сборки и отправления сообщений",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Все сообщения из отправления успешно собраны и отправлены в брокер сообщений",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Неизвестная ошибка",
                            Name = "ErrorUnknown"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Ошибка при подготовке отправления",
                            Name = "ErrorOccuredWhilePreparing"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Ошибка при сборе данных для одного из сообщений в отправлении",
                            Name = "ErrorOccuredWhileCollectingDataForMessage"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Ошибка при публикации одного из сообщений в отправлении",
                            Name = "ErrorOccuredWhilePublishingMessage"
                        });
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.MessageFailure", b =>
                {
                    b.HasOne("NsiTransfer.DAL.Db.Entities.Message", "Message")
                        .WithOne("MessageFailure")
                        .HasForeignKey("NsiTransfer.DAL.Db.Entities.MessageFailure", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.PolynomObject", b =>
                {
                    b.HasOne("NsiTransfer.DAL.Db.Entities.Message", "Message")
                        .WithMany("PolynomObjects")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NsiTransfer.DAL.Db.Entities.Message", b =>
                {
                    b.Navigation("MessageFailure");

                    b.Navigation("PolynomObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
