<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NsiTransfer.Contract\NsiTransfer.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27">
      <!-- <PrivateAssets>all</PrivateAssets> -->
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

    <ItemGroup>
    <Reference Include="Ascon.Polynom.Web.Api.Data">
      <HintPath>..\libs\AsconLibs-05-06-26\Ascon.Polynom.Web.Api.Data.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
